# Generated by Django 5.2.6 on 2025-09-03 22:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tiff', 'bmp', 'webp'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('language_mode', models.CharField(choices=[('en', 'English'), ('multi', 'Multilingual')], default='multi', max_length=10)),
                ('doc_type', models.CharField(choices=[('default', 'Default'), ('labs', 'Labs (tables)')], default='default', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=10)),
                ('ocr_text', models.TextField(blank=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
